FROM node:lts-alpine

# install simple http server for serving static content
RUN npm install -g http-server

WORKDIR /frontend
# Copy these first and install to take advantage of docker-caching when we only make code changes
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

EXPOSE 8080
CMD [ "http-server", "dist" ]
