version: '3.0'
services:
    backend:
        build: ./backend
        container_name:  backend
        restart: always
        volumes:
            - './backend:/backend'
        ports:
            - "5000:5000"

    frontend:
        build: ./frontend
        container_name: frontend
        restart: always
        volumes:
            - ./frontend/nginx-http.conf:/etc/conf.d/default.conf
            - './frontend:/frontend'
        ports:
            - "80:80"
