version: '3.0'
services:
    backend:
        build: ./backend
        container_name:  backend
        restart: always
        volumes:
            - './backend:/backend'
        expose:
            - 5000
        ports:
            - "5000:5000"

    frontend:
        build: ./frontend
        container_name: frontend
        restart: always
        environment:
            - HEY=hey
        volumes:
            - './frontend:/frontend'
        ports:
            - "80:80"
            - "8888:5000"
