version: '3.0'
services:
    backend:
        build: ./backend
        container_name:  backend
        restart: always
        volumes:
            - './backend:/backend'
        expose:
            - 8080

    frontend:
        build: ./frontend
        container_name: frontend
        restart: always
        volumes:
            - './frontend:/frontend'
        ports:
            - "80:80"
